name: test
on:
    pull_request:
        types: [opened, synchronize]
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                go-version: [1.16]
        name: ${{ matrix.os }} test
        steps:
            - uses: actions/checkout@v2
            - name: test
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}
            - name: get deps
              run: go get -v -t -d ./...
            - name: run test
              run: go test -v ./...
