name: test
on: push
jobs:
    linux:
        name: linux test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: test
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16
            - name: get deps
              run: go get -v -t -d ./...
            - name: run test
              run: go test -v ./...
